CREATE DATABASE IF NOT EXISTS servicio_web_auth
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE servicio_web_auth;

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
