spring.application.name=sistema-monitoreo-backend

# Puerto
server.port=${PORT:8080}

# =========================
# MySQL
# =========================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:monitoreo_cultivo}?sslMode=REQUIRED
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate puede detectar MySQL autom\u00c3\u00a1ticamente
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# JSON
# =========================
spring.jackson.serialization.write-dates-as-timestamps=false

# =========================
# WebSocket
# =========================
spring.websocket.allowed-origins=${FRONTEND_URL:http://localhost:8081}
